config/urls.py
from django.contrib import admin
from django.urls import include, path  # 追加：includeをimport

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),  # 追加：includeメソッドでurl設定を追加
]

diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('diary/create/', views.DiaryCreateView.as_view(), name='diary_create'),
    path('diary/create/complete/', views.DiaryCreateCompleteView.as_view(),name='diary_create_complete'),
    path('diary/list/', views.DiaryListView.as_view(), name='diary_list'),
    path('diary/detail/<uuid:pk>/', views.DiaryDetailView.as_view(), name='diary_detail'),
    path('diary/update/<uuid:pk>/', views.DiaryUpdateView.as_view(), name='diary_update'),
    path('diary/delete/<uuid:pk>/', views.DiaryDeleteView.as_view(), name='diary_delete'),
]

diary/models.py
from django.db import models
from django.utils import timezone
import uuid
 
 
class Diary(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(verbose_name='日付', default=timezone.now)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    text = models.CharField(verbose_name='本文', max_length=200)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)

diary/forms.py
from django import forms
from .models import Diary

class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('date', 'title', 'text')

diary/views.py
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.urls import reverse_lazy

from diary.forms import DiaryForm
from diary.forms import Diary
from django.utils import timezone


class IndexView(TemplateView):
    template_name = 'index.html'


class DiaryCreateView(CreateView):
    template_name = 'diary_create.html'
    form_class = DiaryForm
    success_url = reverse_lazy('diary:diary_create_complete')


class DiaryCreateCompleteView(TemplateView):
    template_name = 'diary_create_complete.html'


class DiaryListView(ListView):
    template_name = 'diary_list.html'
    model = Diary


class DiaryDetailView(DetailView):
    template_name = 'diary_detail.html'
    model = Diary


class DiaryUpdateView(UpdateView):
    template_name = 'diary_update.html'
    model = Diary
    fields = ('date', 'title', 'text')
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.update_at = timezone.now()
        diary.save()
        return super().form_valid(form)

class DiaryDeleteView(DeleteView):
    template_name = 'diary_delete.html'
    model = Diary
    success_url = reverse_lazy('diary:diary_list')

templates/base.html
<!DOCTYPE html>
<html lang="jp">

<head>
    <meta charset="UTF-8">
    <title>MyDjangoApp</title>
</head>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

templates/diary_create.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">投稿。</button>
    </form>
{% endblock %}

templates/diary_create_complete.html
{% extends 'base.html' %}
{% block content %}
    <p>日記の投稿が完了しました！</p>
    <a href="{% url 'diary:index' %}">トップへ戻る。</a>
{% endblock %}

templates/diary_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1>日記の削除</h1>
    <form method="post">
        {% csrf_token %}
        <p>{{ diary.date }} {{ diary.text }} を削除します。</p>
        <input type="submit" value="削除">
    </form>
{% endblock %}

templates/diary_detail.html
{% extends 'base.html' %}
{% block content %}
    <p>{{ diary.date }}</p>
    <p>{{ diary.title }}</p>
    <p>{{ diary.text }}</p>
    <p>{{ diary.created_at }}</p>
    <a href="{% url 'diary:diary_update' diary.pk %}">編集</a>
    <a href="{% url 'diary:diary_delete' diary.pk %}">削除</a>
    <a href="{% url 'diary:index' %}">戻る</a>
{% endblock %}

templates/diary_list.html
{% extends 'base.html' %}
{% block content %}
    {% for diary in diary_list %}
    <p>
        {{ diary.date}}
        <a href="{% url 'diary:diary_detail' diary.pk %}">{{ diary.title }}</a>
    </p>
    {% endfor %}
    <a href="{% url 'diary:index' %}">戻る</a>
{% endblock %}

templates/diary_update.html
{% extends 'base.html' %}
{% block content %}
    <h1>日記の編集</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="保存">
    </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Diary App by Django</h1>
<h2><a href="{% url 'diary:diary_create' %}">日記の投稿</a></h2>
<h2><a href="{% url 'diary:diary_list' %}">日記の一覧</a></h2>
{% endblock %}